MinimumStatiqWebVersion-CleanBlog: "1.0.0-beta.36"
SiteTitle: پادکست کودک من
PageTitle: |
  =>
  {
    string siteTitle = Context.GetString("SiteTitle");
    string title = GetString("Title");
    return string.IsNullOrWhiteSpace(siteTitle) ? title : (string.IsNullOrWhiteSpace(title) ? siteTitle : $"{siteTitle} - {title}");
  }
Copyright: => $"Copyright © {DateTime.Now.Year}"
PostSources: posts/**/*
IsPost: => Outputs.FilterSources(Context.GetString("PostSources")).ContainsById(Document)
Layout: /_layout.cshtml
GenerateSearchIndex: true